[package]
name = "gbaemu-core"
version = "0.1.0"
edition = "2021"

[dependencies]
gbaemu-common.workspace = true
gbaemu-rom.workspace = true
gbaemu-ppu.workspace = true
gbaemu-cpu.workspace = true

winit = { workspace = true }
pixels = { workspace = true }
